### ISSUE TITLE
Предлагаю пакет для работы с публикациями

### ISSUE THREAD

**Issue by sergey-romanov** [govdesign/awesome-gov#1]
Предлагаю разработанный нашей командой проект для организации контента в крупных информационных порталах.
Описательная страница проекта http://excentrics.github.io/publication-backbone/ 
Прямая ссылка исходных кодов на github - https://github.com/Excentrics/publication-backbone 
Пакет имеет гибкие возможности по управлению публикациями (статьями, новостями, документами и т.п.), их структурированию, поиску, отбору и фильтрации. Включает в себя большое количество плагинов, которые позволяют добиваться практически любого желаемого оформления публикаций. Есть возможность встраивания графических, текстовых материалов любой сложности, подборки публикаций, возможность подключения внешних систем комментариев, а также выборки различных шаблонов в зависимости от типов публикаций. Имеет систему адаптивной подстройки контента в зависимости от типа плагинов (например, несколько размещенных подряд в тексте картинок оформятся как галерея) 
В качестве системы верстки используется Bootstrap 3, все шаблоны полностью адаптивны и нормально выглядят на большинстве устройств. Базовые шаблоны включенные в проект содержат всё необходимое с точки зрения сайта государственных органов, включая версию для людей с ограниченными возможностями. Пример где это работает http://www.beladm.ru

**Comment by kalloc** [comment]
@sergey-romanov у вас очень интересное начинание.  
Можно вас попросить сделать пример проекта, который можно было бы легко склонировать и запустить?
Мы бы тогда добавили ссылку и на приложение и на пример использования

**Comment by sergey-romanov** [comment]
Да, но на это потребуется некоторое время. Текущие проекты сделанные на этом движке не могу отдать, так как они клиентские, а сделать «рыбу» для быстрого разворота я могу. Напишу когда будет готово.

**Comment by kalloc** [comment]
@sergey-romanov видим что у вас не получается сделать пример, давайте добавим ссылку просто на проект, но вы постарайтесь пример сделать. Людям сложно оценивать без примеров

**Comment by sergey-romanov** [comment]
До конца недели выложу готовый пример

**Comment by sergey-romanov** [comment]
Добрый день, отдельный демо проект подготовлен, инструкция по разворачиванию демо проекта с тестовыми данными приложена к пакету, описание начинается с секции https://github.com/Excentrics/publication-backbone/blob/master/README.md#quick-start-sample-demo-project

**Comment by kalloc** [comment]
@sergey-romanov спасибо большое, опубликовали
